<?php 
/**
 * @file
 * Adds a Facebook feed processor to the Feeds module.
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function feeds_facebook_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_facebook_feeds_plugins() {
  $info = array();
  $info['FeedsFacebookParser'] = array(
    'name' => 'Facebook parser',
    'description' => 'Parse Facebook feeds.',
    'help' => '',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsFacebookParser',
      'file' => 'FeedsFacebookParser.inc',
      'path' => drupal_get_path('module', 'feeds_facebook'),
    ),
  );
  return $info;
}