<?php 

/**
 * @file
 * Adds a YouTube feed processor to the Feeds module.
 * 
 * @see http://drupal.org/node/622696
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function feeds_youtube_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_youtube_feeds_plugins() {
  $info = array();
  $info['FeedsYoutubeParser'] = array(
    'name' => 'YouTube parser',
    'description' => 'Parse YouTube feeds.',
    'help' => 'Use PHP SimpleXML parser to parse YouTube feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsYoutubeParser',
      'file' => 'FeedsYoutubeParser.inc',
      'path' => drupal_get_path('module', 'feeds_youtube'),
    ),
  );
  return $info;
}
